### ISSUE TITLE
CredReuseRejectedException.java - Add copyright and license header.

### ISSUE THREAD

**Issue by trbehera** [fido-device-onboard/pri-fidoiot#142]
CredReuseRejectedException.java - Add copyright and license header.

_Originally posted by @trbehera in https://github.com/secure-device-onboard/pri-fidoiot/pull/139#discussion_r578910015_

**Comment by DukeDavis12** [comment]
<img width="507" alt="image" src="https://github.com/fido-device-onboard/pri-fidoiot/assets/52932399/d75c5eba-296a-40e2-9fc0-b28476fe3e81">
copyright and license header is present now.
