### ISSUE TITLE
This unit-test is disabled. It should be enabled in a subsequent PR.

### ISSUE THREAD

**Issue by trbehera** [fido-device-onboard/pri-fidoiot#186]
This unit-test is disabled in TO2StorageTest. It should be enabled in a subsequent PR.

_Originally posted by @trbehera in https://github.com/secure-device-onboard/pri-fidoiot/pull/165#discussion_r602417093_

**Comment by DukeDavis12** [comment]
TO2StorageTest is removed as we moved to Hibernate Framework.
