### ISSUE TITLE
[BUG] Error-Type 255/Catch-all endpoint not working

### ISSUE THREAD

**Issue by kuriakosejohn** [fido-device-onboard/pri-fidoiot#265]
**Describe the bug**
Catch-all endpoint not mapped & handled correctly on the server side, this is blocking clients from reporting errors.

**To Reproduce**
1. Simulate an error(may be wrong MTU size) in any of the protocols(DI/TO1/TO0/TO2) client fail with http error endpoint not available

**Expected behavior**
Clients should be able to register errors with server by making an http request.
Servers should be able to send error responses back to clients as response to http requests.

**Comment by grbean** [comment]
I'm afraid I don't understand the assertion.

When you say 'clients should be able to register errors with server', what do you mean?
