### ISSUE TITLE
[pri-fidoiot] Proxy settings for owner need to be set explicitly when using a proxy 

### ISSUE THREAD

**Issue by v-vasavi** [fido-device-onboard/pri-fidoiot#476]
**Describe the bug**
To configure Owner's proxy settings uncomment the following code section in service.yml file and replace the fields with proper proxy details.
# Uncomment the below properties for proxy setup
#http.proxyHost: $(http_host)
#http.proxyPort: $(http_port)
#https.proxyHost: $(https_host)
#https.proxyPort: $(https_port)
#http.nonProxyHosts: $(no_proxy)
Sample proxy setup:
http.proxyHost: proxy.mycompany.com
http.proxyPort: 8119
https.proxyHost: proxy.mycompany.com
https.proxyPort: 8129
http.nonProxyHosts: localhost | some-ip | *.mycompany.com
**To Reproduce**
Run TO0
When inside a proxy environment, owner is unable to contact RV during TO0.

**Expected behavior**
TO0 should complete successfully

**Screenshots**

**Test Environment**
Provide details about your test environment.

**Additional context**

**Comment by DukeDavis12** [comment]
It's up to the network proxy configuration to allow internal communication via proxy.
