### ISSUE TITLE
[DB authentication failure] Docker containers seem to only work with empty passwords - with generate creds, they cannot connect to DB

### ISSUE THREAD

**Issue by cslev** [fido-device-onboard/pri-fidoiot#526]
**Describe the bug**
The steps with generating the credentials and copying the corresponding `service.env` files into the respective component directories cause the docker containers to fail to start.
They fail by connecting to the database, i.e., for some reason, those new credentials do not work, and the DB can only accept connections with empty passwords.

**To Reproduce**
1. Follow the steps in the README.md file
2. generate the credentials with the keygen script and copy the service.env files into the respective component folders
3. follow the `docker-compose`-based approaches and see whether the containers come up - after finishing the compilation, `docker ps -a` shows the containers as `exited.`
4. Issue `docker logs pri-fdo-<component>` to see the error logs 

**Docker logs output**
```
03:37:17.033 [INFO ] HHH000400: Using dialect: org.hibernate.dialect.H2Dialect
03:37:17.067 [WARN ] SQL Error: 28000, SQLState: 28000
03:37:17.068 [ERROR] Wrong user name or password [28000-210]
03:37:17.069 [ERROR] database session factory setup failed
```

**Test Environment**
Regular Ubuntu Linux

**Additional context**
NA

**Comment by cslev** [comment]
After setting up the containers with the empty passwords, accessing the manufacturer service fails with authentication error.
This is the instruction from the README.md
```
POST https://host.docker.internal:8038/api/v1/rvinfo (or http://host.docker.internal:8039/api/v1/rvinfo) The post body content-type header text/plain Authorization DIGEST with "apiUser" and api_password defined in the manufacturer's service.env POST content
```
Checking the `service.yml` of the manufacturer, I can see the username is `apiUser` (just as indicated above), but the empty password does not work and I get an Error 401:
```
WWW-Authenticate: Digest realm="Authentication required", qop="auth", nonce="1658464401861:5ec2d32654920cc8cb25ad3bff2f990f", opaque="3B2D5B875381C78ACF4EC0AA71A54F1F"
Content-Type: text/html;charset=utf-8
Content-Language: en
Content-Length: 673
Date: Fri, 22 Jul 2022 04:33:21 GMT
Keep-Alive: timeout=20
Connection: keep-alive
```

Did anyone encounter this behavior?

**Comment by DukeDavis12** [comment]
@cslev  Thanks for your Contribution. Can you delete the existing db file from demo/<component>/app-data folder?

**Comment by cslev** [comment]
Thanks for the comment. The trick indeed work for my first issue!
So, I deleted both `emdb.mv.db` and `emdb.trace.db` files, copied the generated `creds/.` into their corresponding directories, and rebuild the containers from scratch to be sure.
The containers came up without any error, so it worked.

However, when I try to Create Ownership Vouchers using Individual Component Demos, then I bump into the same error. 
I tried both using `HTTP` and `HTTPS`, `POST` message, set authentication to `digest`, and `content-type` to `text/plain`.
The browser (where my REST client sits) even ask for the password (so the URLs are indeed working), but then the response is similar:
```
Response 401

WWW-Authenticate: Digest realm="Authentication required", qop="auth", nonce="1658891804361:fe5f0888c75456e714a1ff8f994c2bcf", opaque="7C912350EAB1868F3D8BAD04BCA34D36"
Content-Type: text/html;charset=utf-8
Content-Language: en
Content-Length: 673
Date: Wed, 27 Jul 2022 03:16:44 GMT
Keep-Alive: timeout=20
Connection: keep-alive
```
I have a sense, though, that something might be still working, because if I supply the wrong password (e.g., empty or randomly chosen other passwords from the `service.env` file), the browser immediately asks for the credentials again. 
Once I set the correct `api_password`, then I get back the message above...but then why HTTP error 401 (Unauthorized access).
Sounds weird.

**Comment by cslev** [comment]
I still tried to continue the tutorial, and run `java -jar device.jar` with the modified `service.yml` pointing to `di-url: http://host.docker.internal:8039`.
The output is still the same as in the beginning. The debug message still says T01 only with the built-in host of `http://host.docker.internal:8080`.

```
12:12:26.842 [WARN ] Using SSL self-signed certificate trust strategy for Http Clients
12:12:27.011 [INFO ] Starting Fdo Device
12:12:27.085 [INFO ] credentials loaded, GUID is caf69057-be3f-4bc4-9f77-af59e0461a07
12:12:27.162 [INFO ] RVBypass flag not set, Starting TO1.
12:12:27.163 [INFO ] TO1 URL is http://host.docker.internal:8080
12:12:27.179 [INFO ] Type 30 [h'CAF69057BE3F4BC49F77AF59E0461A07', [-7, h'']]
12:12:27.393 [INFO ] Type 31 [h'0BDABB02A4414F80868E68572399A8F6', [-7, h'']]
12:12:27.927 [INFO ] Type 32 [h'A10126', {}, h'A20A500BDABB02A4414F80868E68572399A8F61901005101CAF69057BE3F4BC49F77AF59E0461A07', h'F4F5F13E995AA351D319B6B3773B52A0F268581581F1B956A705BB91B56377DE8689E7F460416477DF7C1ECCCF31629EE442932ACF283F89F87E4714C845E2A9']
12:12:28.032 [INFO ] Type 255 [6, 32, "guid: caf69057-be3f-4bc4-9f77-af59e0461a07", 1658895148, 2216149814]
12:12:28.032 [INFO ] Starting Fdo Completed

```

**Comment by DukeDavis12** [comment]
> I still tried to continue the tutorial, and run `java -jar device.jar` with the modified `service.yml` pointing to `di-url: http://host.docker.internal:8039`. The output is still the same as in the beginning. The debug message still says T01 only with the built-in host of `http://host.docker.internal:8080`.
> 
> ```
> 12:12:26.842 [WARN ] Using SSL self-signed certificate trust strategy for Http Clients
> 12:12:27.011 [INFO ] Starting Fdo Device
> 12:12:27.085 [INFO ] credentials loaded, GUID is caf69057-be3f-4bc4-9f77-af59e0461a07
> 12:12:27.162 [INFO ] RVBypass flag not set, Starting TO1.
> 12:12:27.163 [INFO ] TO1 URL is http://host.docker.internal:8080
> 12:12:27.179 [INFO ] Type 30 [h'CAF69057BE3F4BC49F77AF59E0461A07', [-7, h'']]
> 12:12:27.393 [INFO ] Type 31 [h'0BDABB02A4414F80868E68572399A8F6', [-7, h'']]
> 12:12:27.927 [INFO ] Type 32 [h'A10126', {}, h'A20A500BDABB02A4414F80868E68572399A8F61901005101CAF69057BE3F4BC49F77AF59E0461A07', h'F4F5F13E995AA351D319B6B3773B52A0F268581581F1B956A705BB91B56377DE8689E7F460416477DF7C1ECCCF31629EE442932ACF283F89F87E4714C845E2A9']
> 12:12:28.032 [INFO ] Type 255 [6, 32, "guid: caf69057-be3f-4bc4-9f77-af59e0461a07", 1658895148, 2216149814]
> 12:12:28.032 [INFO ] Starting Fdo Completed
> ```

Can you try with this PR? https://github.com/secure-device-onboard/pri-fidoiot/pull/529

**Comment by DukeDavis12** [comment]
> ), the browser immediately asks for the credentials again.
> Once I set the correct `api_password`, then I get back the message above...

Which client are you using for your Digest request creation?

**Comment by cslev** [comment]
> 

Thanks, I will try!
If that is only about the fallback mechanism that I already tried to overcome such an issue by setting the host.docker.internal to my localhost IP in `/etc/hosts` file.

**Comment by cslev** [comment]
> > ), the browser immediately asks for the credentials again.
> > Once I set the correct `api_password`, then I get back the message above...
> 
> Which client are you using for your Digest request creation?

I tested with RESTer extension of firefox. I have been using it for a while and it always worked as expected. But I am a fan of postman too. So, will try with postman; maybe it will work out with it. Keep you posted. Thanks

**Comment by DukeDavis12** [comment]
> > > ), the browser immediately asks for the credentials again.
> > > Once I set the correct `api_password`, then I get back the message above...
> > 
> > 
> > Which client are you using for your Digest request creation?
> 
> I tested with RESTer extension of firefox. I have been using it for a while and it always worked as expected. But I am a fan of postman too. So, will try with postman; maybe it will work out with it. Keep you posted. Thanks

Can you try with Postman?  We test with postman and cURL.

**Comment by cslev** [comment]
I tried with postman, same error 401:
See postman output [here](https://ibb.co/c1qpDj4)

**Comment by DukeDavis12** [comment]
Are you running the service as `java -jar aio.jar` ?

**Comment by DukeDavis12** [comment]
> I tried with postman, same error 401: See postman output [here](https://ibb.co/c1qpDj4)

Are you running the service as java -jar aio.jar ?

**Comment by cslev** [comment]
Nope, I am running them in containers following the docker-compose-based instructions. All containers are up and running properly. 
This part: `Staring the FDO PRI HTTP Device` works as expected. I could also telnet to the services running on the specified ports. So, there should not be any issue with the services running.

**Comment by DukeDavis12** [comment]
1. Restart the service using `docker-compose down && docker-compose up --build`
or
2. Can you try updating the password in the service.yml file's `$(api_password)` field ? and restart the service.

**Comment by DukeDavis12** [comment]
++, check whether the service.env file contains the correct api_password.

**Comment by cslev** [comment]
I just checked all! rebuild images, double-checked the passwords in the corresponding services.env files, but still the same result.

**Comment by cslev** [comment]
[screenshot](https://ibb.co/CJj6BXk)

**Comment by DukeDavis12** [comment]
> [screenshot](https://ibb.co/CJj6BXk)

if check the post address; it is 127.0.01:8039. Shouldn't it be 127.0.0.1:8039 ?

**Comment by cslev** [comment]
Oh, yes. There was a typo, however, it did not make any difference. Postman figured out the right IP address. Otherwise, I would have gotten a different networking error instead of error 401.
Just to be sure, I put that missing dot there, but nothing changed...
