### ISSUE TITLE
Where to configure payload to be transferred to the device in TO2 protocol

### ISSUE THREAD

**Issue by MarioRossi37** [fido-device-onboard/pri-fidoiot#597]
Hi,
I followed the guide for aio and device components installation but I can't figure out how to make the device download a payload decided by me. Is there a configuration file? Do I have to insert an entry in the db? Where do I have to set ServiceInfo objects?

Thank you.

**Comment by shrikant1407** [comment]
Yes, you have to upload the file to the db first. More info here https://github.com/fido-device-onboard/pri-fidoiot/tree/master/component-samples/demo#enabling-serviceinfo-transfer
