### ISSUE TITLE
[BUG] Connection fails when connecting to external FDORV

### ISSUE THREAD

**Issue by DukeDavis12** [fido-device-onboard/pri-fidoiot#619]
**Describe the bug**
Connection fails when connecting to external FDORV

**To Reproduce**
1. Set rv info([[[5," fdorv.duckdns.org"],[3,8040],[12,1],[4,8040]]]) to manufacturer server 
2. Perform TO0
3. You can see that MSG/20 fails

**Expected behavior**
Establish a connection and perform TO0.

**Screenshots**
![image](https://github.com/fido-device-onboard/pri-fidoiot/assets/52932399/092dad82-4a1d-4a2a-9dc0-04db6e853e75)

**Comment by DukeDavis12** [comment]
We were able to solve the issue with TO0.  Blanking out the api-user.pem in the owners secrets folder resolves the issue.   The owner is trying to do mTLS with the RV server because it finds certificates in the api-user.pem.   The owner itself does not need this file but you do api-user.pem certificates to make curl API clalls.   We moved api-user.pem and ca-certs.pem into the owner directory for API calls and blanked the api-user.pem in secrets and TO0 is now working.

**Comment by cynex-k** [comment]
Hey I did blanking out the api-user.pem 
and still got an error 
```
11:36:04.324 [INFO ] Health check invoked at Mon Nov 11 11:36:04 GMT 2024
11:36:34.417 [INFO ] Health check invoked at Mon Nov 11 11:36:34 GMT 2024
11:37:04.495 [INFO ] Health check invoked at Mon Nov 11 11:37:04 GMT 2024
11:37:34.595 [INFO ] Health check invoked at Mon Nov 11 11:37:34 GMT 2024
11:38:04.264 [INFO ] TO0 URL is https://rv.cloud:8041
11:38:04.264 [INFO ] Type 20 []
11:38:04.267 [INFO ] instruction failed.
11:38:04.267 [INFO ] moving to next instruction
11:38:04.268 [INFO ] TO0 URL is https://x.x.x.x:8041 # censored 
11:38:04.268 [INFO ] Type 20 []
11:38:04.298 [INFO ] instruction failed.
11:38:04.300 [INFO ] moving to next instruction
11:38:04.301 [INFO ] all instructions exhausted
11:38:04.302 [ERROR] To0 client error Unable to establish connection with FDO Server
```
here what I set rv info
```[[[5,"rv.cloud"],[3,8040],[12,2],[2,x.x.x.x],[4,8041]]]```
